[build]
  publish = "."

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'none'; base-uri 'self'; form-action 'none'; object-src 'none'; frame-ancestors 'none'; style-src 'unsafe-inline'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "DENY"
    Cache-Control = "public, max-age=86400"

# Force HTTPS
[[redirects]]
  from = "http://blank-page-demo.netlify.app/*"
  to = "https://blank-page-demo.netlify.app/:splat"
  status = 301
  force = true